### ISSUE TITLE
Inclusion of the CustomResourceDefinition type

### ISSUE THREAD

**Issue by fxierh** [openshift/api#1712]
Currently the CustomResourceDefinition type is not included in this repo.
Any chance to incorporate this one into kubeSchemeBuilder ?

**Comment by JoelSpeed** [comment]
I believe the list is supposed to mirror https://github.com/kubernetes/client-go/blob/5a0a4247921dd9e72d158aaa6c1ee124aba1da80/kubernetes/scheme/register.go#L83-L135, which does not include the CRD types. They can easily be added to the scheme separately if required though. I expect we don't add it to the scheme by default since most operators do not need access to the CRD types within their scheme.

Personally, I tend to build up my own scheme in operators based on the types I know that I need, this reduces the memory footprint of the scheme.
