### ISSUE TITLE
ImageStream API should not re-register SecretList

### ISSUE THREAD

**Issue by ctron** [openshift/api#270]
Occording to @DirectXMan12, in comment https://github.com/kubernetes-sigs/controller-runtime/issues/362#issuecomment-477767432, OpenShift should not re-register `corev1.SecretList` under its own Group/Version.

This breaks the controller-runtime and causes: https://github.com/kubernetes-sigs/controller-runtime/issues/362

https://github.com/openshift/api/blob/b772cc93d057f30f40f93347a043c3bcef11d268/image/v1/register.go#L48

**Comment by deads2k** [comment]
In general, cross registering types is an acceptable thing to do.  That's why when the scheme maps them, it allows for multiple matches https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/runtime/scheme.go#L236 .

It allows serialization of an existing type into a new group.  We make use of cross registration for several types in `k8s.io/apimachinery/apis/meta/v1` and it is a generically acceptable concept.

**Comment by alvaroaleman** [comment]
/reopen
still not fixed.
