### ISSUE TITLE
Make mirror-by-digest-only option configurable through ImageContentSourcePolicy 

### ISSUE THREAD

**Issue by mvazquezc** [openshift/api#636]
When working with disconnected environments, sometimes you need to define multiple ImageContentSourcePolicies, some of them are used by apps / manifests that don't use digests when pulling the images.

Currently, all configurations are added with `mirror-by-digest-only` property set to `true`. It will be nice if this property could be configured using the ImageContentSourcePolicy.

Thanks,

**Comment by jparrill** [comment]
Some examples of this method:

- As you could see, there are already applied some ICSP already on the current cluster:
```
[kni@bm-cluster-1-hyper ipv6]$ oc get imagecontentsourcepolicy
NAME                      AGE
community-operators       62m
image-policy-0            62m
image-policy-1            62m
open-cluster-management   62m
redhat-operators          62m
```

In a Master, by default you will have this config (head -10 of the `/etc/containers/registries.conf` file):

```
[root@openshift-master-0 core]# cat /etc/containers/registries.conf | head -10
unqualified-search-registries = ["registry.access.redhat.com", "docker.io"]

[[registry]]
  prefix = ""
  location = "docker.io/apache/camel-k"
  mirror-by-digest-only = true

  [[registry.mirror]]
    location = "bm-cluster-1-hyper.e2e.bos.redhat.com:5000/apache/camel-k"
...
...
...
```

And as you see on every entry from `oc release mirror...` command will include the attribute `mirror-by-digest-only = true` and also is included in the main section called `[registries]`, the thing is, if you add a separated ICSP this option will be included by default and there is not any way via API to configure this parameter.

The use case is easy, think in a non-released product (ACM) and on a disconnected deployment. We need to provide a way through the API to configure these parameters in order to avoid access the nodes by ssh and modify the file manually.

**Comment by a-dawg** [comment]
I am having the same issue, this would be very useful when using internal image registries. There is no other way to bypass the machineconfig cluster operator and degraded it...

**Comment by reggie-k** [comment]
High priority for our org as well.
Any updates?

**Comment by bdurrow** [comment]
As best I can tell, as of 4.10, [OCPNODE-717](https://issues.redhat.com/browse/OCPNODE-717) remains open and unimplemented.  Until completed, `ImageContentPolicy` has no effect

**Comment by nate-duke** [comment]
somebody who has permissions to do so should probably tell the bot to reopen this issue.

**Comment by jonasbartho** [comment]
I can confirm this is still an issue in OKD4.11
